apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: kNsrVjfukEpdlv830ObleTZERGAvnVm/n5g4Z5yQ0RM=
      - identity: {}

