apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: crash-course
spec:
  replicas: 1
  selector:
    matchLabels: { app: auth-service }
  template:
    metadata:
      labels: { app: auth-service }
    spec:
      containers:
      - name: auth-service
        image: saiyam911/auth-service
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          value: postgresql://user:password@postgres:5432/dbname
        ports: [{ containerPort: 8080 }]

