# clusterissuer-letsencrypt.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let’s Encrypt production endpoint
    server: https://acme-v02.api.letsencrypt.org/directory
    email: saiyam911@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: http
                namespace: kgateway-system
                kind: Gateway

