apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: crash-course-gateway
  namespace: kgateway-system
  annotations:
    # tells cert-manager to mint a cert for course.kubesimplify.com
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: kgateway
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: course.kubesimplify.com
      tls:
        mode: Terminate
        certificateRefs:
          # cert-manager will create this Secret for you
          - name: crash-course-tls

