apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: crash-course-gateway
  namespace: crash-course
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: kgateway  # Change to 'nginx' if available
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: course.kubesimplify.com
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    hostname: course.kubesimplify.com
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: crash-course-tls
        kind: Secret
        group: ""
