apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-route
  namespace: crash-course
spec:
  parentRefs:
  - name: crash-course-gateway
    namespace: crash-course
    sectionName: https
  hostnames:
  - course.kubesimplify.com
  rules:
  - backendRefs:
    - name: frontend
      port: 80
