apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: crash-course-route-https
  namespace: crash-course
spec:
  parentRefs:
    - name: crash-course-gateway
      namespace: kgateway-system
      sectionName: https
  hostnames:
    - course.kubesimplify.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: frontend
          port: 80

