apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: crash-course
spec:
  instances: 3
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: dbname
      owner: user
      # This section will run your SQL script after the database is created
      postInitApplicationSQLRefs:
        configMapRefs:
        - name: init-sql # The name of your existing ConfigMap
          key: init.sql   # The key in the ConfigMap that holds the SQL script
